apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-deployment-authors
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authors-pod
  template:
    metadata:
      labels:
        app: authors-pod
    spec:
      containers:
      - name: authors
        image: orsanaw/library-app-authors:1.6
        ports:
        - containerPort: 8000